language: python
python:
  - "3.7"

services:
  - docker

before_install:
  - docker build -t tails5555/hub-py-test:latest .
  - docker ps -a
  - docker run -d -p 5000:5000 tails5555/hub-py-test /bin/sh -c "cd /app; nohup python app.py &;"
  - docker push tails5555/hub-py-test:latest

install: "pip install -r requirements.txt"

script: 
  - "nohup python app.py &"
  - "pytest"