language: python
python:
  - "3.7"

services:
  - docker

before_install:
  - docker build -t tails5555/docker-hub-test:latest .
  - docker run -d -p 127.0.0.1:80:5000 tails5555/docker-hub-test /bin/sh -c "cd /app; nohup python app.py &;"
  - docker ps -a
  - docker run -d -p 127.0.0.1:80:5000 tails5555/docker-hub-test /bin/sh -c "cd /app; pytest &;"

install: "pip install -r requirements.txt"

script: 
  - "nohup python app.py &"
  - "pytest"